name: Update Golf Data

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Force fetch latest version
        run: |
          git fetch origin
          git reset --hard origin/main


      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests

      - name: Run tournament results scraper
        run: python tournament_results.py

      - name: List output files
        run: |
          pwd
          s -R



      # temporarily disabled for debugging:
      # - name: Run individual tournament results scraper
      #   run: python individual_tournament_results.py

      # - name: Run individual player stats scraper for active players
      #   run: python player_individual_stats.py

      - name: Commit and push updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git diff --quiet && echo "No changes to commit" && exit 0
          git commit -m "Update golf data [auto]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
