name: Update Golf Data

# Temprorarily disabled to save $$$
on:
  # push:
  #   branches: [main]
  # schedule:
  #   - cron: '0 6 * * 1'
  workflow_dispatch:

permissions: # allows github actions to commit changes
  contents: write

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Force fetch latest version
        run: |
          git fetch origin
          git reset --hard origin/main


      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests
      
      - name: Run get active players script
        run: python get_active_players.py

      - name: Run tournament results scraper
        run: python tournament_results.py

      - name: Run individual tournament results scraper
        run: python individual_tournament_results.py

      - name: Run individual player stats scraper for active players
        run: python player_individual_stats.py
      
      - name: Run enriched player details scraper
        run: python get_players.py

      # Caution - this takes 20+ minutes to run, ideally do 
      # this locally to prevent excessive GitHub Actions billing
      # - name: Run ChromaDB setup script
      #   run: python chroma_setup.py

      - name: Show Git status and modified files
        working-directory: ${{ github.workspace }}
        run: |
          echo "Working Directory:"
          pwd
          echo "Directory contents:"
          ls -alR
          echo "Git status:"
          git status


      - name: Commit and push updates
        working-directory: ${{ github.workspace }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git status
          git commit -m "Update golf stats data" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
      

